### ISSUE TITLE
Casey Lab 1

### ISSUE THREAD

**Issue by caseybales** [DataScience4Psych/DataScience4Psych#64]
https://github.com/caseybales/lab-01-hello-r.git

**Comment by smasongarrison** [comment]
Thanks! (Lol, I think I was over zealous with the bot)

S. Mason Garrison
Assistant Professor
Quantitative Psychology

Wake Forest University
(she her hers)
Spare computers? -- Help fight COVID-19
<https://foldingathome.org/covid19/>Schedule a one-on-one meeting via
calendly <https://calendly.com/smasongarrison/>

**Comment by smasongarrison** [comment]
Nice job! I added some comments as an issue, but this is satisfactory or whatever that adjective is that I had in the syllabus
