### ISSUE TITLE
Filter question Lab 3

### ISSUE THREAD

**Issue by stephbossert** [DataScience4Psych/DataScience4Psych#68]
I am trying to filter out the nobel laureates for those who have country info. I'm using the code:
filter(is.na(died_date), (gender == "org"), ("country" na.rm = TRUE))
And getting the error:
Error: unexpected symbol in:
"nobel_living <- nobel %>%
filter(is.na(died_date), (gender == "org"), ("country" na.rm"

Does anyone know how to filter out for people who have data for that variable?

**Comment by smasongarrison** [comment]
Ahh lol, I see what you were talking about now! (The welcome message is a bot!)
